version: "3.3"

services:
  mongo:
    image: "quay.io/wekan/mongo:4.4.2-bionic"
    container_name: "mongo"
    command: "mongod --logpath /dev/null --oplogSize 128 --quiet"
    volumes:
      - "/srv/docker-volumes/mongo-db:/data/db"    
      - "/srv/docker-volumes/mongo-dump:/dump"
    restart: unless-stopped      
    networks:
      - docker
             
  wekan:
    image: quay.io/wekan/wekan
    container_name: wekan
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wekan-secure.rule=Host(`wekan.cloud63.fr`)"
      - "traefik.http.routers.wekan-secure.entrypoints=websecure"
      - "traefik.http.routers.wekan-secure.tls.certresolver=myresolver"
      - "traefik.http.services.wekan-secure.loadbalancer.server.port=8080"      
    environment:
      - MONGO_URL=mongodb://mongo:27017/wekan
      - ROOT_URL=https://wekan.cloud63.fr
      - MAIL_URL=smtp://mail.cloud63.fr:25/?ignoreTLS=true&tls={rejectUnauthorized:false}
      - MAIL_FROM=Wekan Notifications <noreply.wekan@mydomain.com>
      - WITH_API=true
      - RICHER_CARD_COMMENT_EDITOR=false
      - CARD_OPENED_WEBHOOK_ENABLED=false
      - BIGEVENTS_PATTERN=NONE
      - BROWSER_POLICY_ENABLED=true
    depends_on:
      - "mongo"
    restart: unless-stopped
    networks:
      - docker      

networks:
  docker:
    external: true 
