version: '3.3'

services:
  rainloop:
    image: hardware/rainloop
    container_name: "rainloop"
    depends_on:
      - mail
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mail-secure.rule=Host(`mail.cloud63.fr`)"
      - "traefik.http.routers.mail-secure.entrypoints=websecure"
      - "traefik.http.routers.mail-secure.tls.certresolver=myresolver"
      - "traefik.http.services.mail-secure.loadbalancer.server.port=8888"
    volumes:
      - "/srv/docker-volumes/rainloop-data:/rainloop/data" 
    restart: unless-stopped
    networks:
      - docker

  mail:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mail
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - "/srv/docker-volumes/mail-data:/var/mail"
      - "/srv/docker-volumes/mail-state:/var/mail-state"
      - "/srv/docker-volumes/mail-log/:/var/log/mail"
      - "/srv/docker-volumes/mail-config/:/tmp/docker-mailserver/"
      - "/srv/docker-volumes/mail-letsencrypt/:/etc/letsencrypt/"
    env_file: /srv/docker-volumes/mail-config/mailserver.env
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: unless-stopped    
    networks:
      - docker    

networks:
  docker:
    external: true
