version: "3.3"

services:
  traefik:
    image: "traefik:v2.3"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=vincent@misson.cloud"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
    networks:
      - proxy    

  portainer:
    image: "portainer/portainer"
    container_name: "portainer"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.lab.misson.cloud`)"
      - "traefik.http.routers.portainer-secure.entrypoints=websecure"
      - "traefik.http.routers.portainer-secure.tls.certresolver=myresolver"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "/srv/docker-volumes/portainer-data:/data"
    restart: unless-stopped
    networks:
      - proxy

  watchtower:
    image: "containrrr/watchtower"
    container_name: "watchtower"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  proxy:
    external: true      