version: "3.3"

services:
  traefik:
    image: "traefik:v2.3"
    container_name: "traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.cloud63.fr`)"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik-secure.service=api@internal"
    ports:
      - "443:443"
    volumes:
      - "/srv/docker-volumes/traefik-traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/srv/docker-volumes/traefik-letsencrypt:/letsencrypt"
    restart: unless-stopped
    networks:
      - docker    

  portainer:
    image: "portainer/portainer-ce"
    container_name: "portainer"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.cloud63.fr`)"
      - "traefik.http.routers.portainer-secure.entrypoints=websecure"
      - "traefik.http.routers.portainer-secure.tls.certresolver=myresolver"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "/srv/docker-volumes/portainer-data:/data"
    restart: unless-stopped
    networks:
      - docker

  watchtower:
    image: "containrrr/watchtower"
    container_name: "watchtower"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
    networks:
      - docker

networks:
  docker:
    external: true      
