version: '3.3'

services:
  bitwarden:
    image: "bitwardenrs/server"
    container_name: "bitwarden"
    environment:
      LOG_FILE: '/data/bitwarden.log'
      SIGNUPS_ALLOWED: 'true'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bitwarden-secure.rule=Host(`bitwarden.cloud63.fr`)"
      - "traefik.http.routers.bitwarden-secure.entrypoints=websecure"
      - "traefik.http.routers.bitwarden-secure.tls.certresolver=myresolver"
    volumes:
      - "/srv/docker-volumes/bitwarden-data:/data"
      - "/srv/docker-volumes/bitwarden-ssl:/ssl"            
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true    
